- type: Conferences/Workshops (Chair)
  venue: 1st Workshop on Reliable Large-Scale Data Management
  additional_info: " - co-located with SRDS'25. PC Chair."
  acronym: RLDM'25
  website: https://rldm.invisiblelab.dev
  year: 2025

- type: Artifact Evaluation Committee Member
  venue: 24th International Conference on Distributed Applications and Interoperable Systems
  acronym: DAIS'25
  website: https://www.discotec.org/2025/dais
  year: 2025

- type: Program Committee Member
  venue: 20th ACM European Conference on Computer Systems
  acronym: EuroSys'25
  website: https://2025.eurosys.org
  additional_info: "[ShadowPC]"
  year: 2025

- type: Artifact Evaluation Committee Member
  venue: 20th European Conference on Computer Systems -- Spring cycle
  acronym: Eurosys'25
  website: https://2025.eurosys.org
  year: 2025

- type: Journals (Reviewer)
  venue: IEEE Transactions on Parallel and Distributed Systems
  acronym: TPDS
  website: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=71
  year: 2024

- type: Journals (Reviewer)
  venue: Science of Computer Programming
  acronym: SCICO
  website: https://www.sciencedirect.com/journal/science-of-computer-programming
  year: 2024

- type: Artifact Evaluation Committee Member
  venue: 22nd International Conference on Distributed Applications and Interoperable Systems
  acronym: DAIS'23
  website: http://www.discotec.org/2023/dais.html
  year: 2023
